<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstracta" nsURI="http://abstracta" nsPrefix="abstracta">
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactoryAbstracta">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstProjectba" upperBound="-1"
        eType="#//Projectba" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstClasifierba" upperBound="-1"
        eType="#//Clasifier" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Projectba">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstPackages" upperBound="-1"
        eType="#//Packageba" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Packageba">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listPackages" upperBound="-1"
        eType="#//Packageba" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstClass" upperBound="-1"
        eType="#//Classba" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Classba" eSuperTypes="#//Clasifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isInterface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifyAcces" eType="#//AccessModifyba"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstRelationshipSourceba"
        upperBound="-1" eType="#//Relationshipba" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstAttributesba" upperBound="-1"
        eType="#//Attributeba" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstRelationshipTargetba"
        upperBound="-1" eType="#//Relationshipba"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstMethodba" upperBound="-1"
        eType="#//Methodba" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationshipba">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAgregation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isContainment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isGeneralization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAssociation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isImplementation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rolS" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rolT" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Classba"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Classba"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clasifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstAttributebaC" upperBound="-1"
        eType="#//Attributeba"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveDataType" eSuperTypes="#//Clasifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attributeba">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classba" eType="#//Classba"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Clasifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifyAcces" eType="#//AccessModifyba"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Methodba">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="retorno" eType="#//Clasifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classba" eType="#//Classba"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lstParametersba" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modifyAcces" eType="#//AccessModifyba"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methodba" eType="#//Methodba"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Clasifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessModifyba">
    <eLiterals name="PUBLIC" value="1"/>
    <eLiterals name="PRIVATE" value="2"/>
    <eLiterals name="PROTECTED" value="3"/>
    <eLiterals name="DEFAULT" value="4"/>
  </eClassifiers>
</ecore:EPackage>
